"""
patch_figure1_dedup_note.py -- corrects a stale annotation on figure1_architecture.png.

figure1_architecture.png (the manuscript's Figure 1) is an externally
produced diagram, not generated by a script in this repository. As
supplied, its dashed callout box read "eventId-based dedup path
implemented here, not yet deployed, not separately shown" -- accurate
when the diagram was made, but stale after the password-hashing and
idempotency fixes were deployed to the live backend on 28 August 2026
(docs/idempotency_and_password_hashing.md). Left uncorrected, the figure
would have visibly contradicted the manuscript's own text and caption.

This script whites out that callout box and redraws it with the corrected
wording, in place, leaving the rest of the diagram untouched. It is not
meant to be re-run against a fresh copy of the source diagram without
re-checking the box coordinates by eye first, the same caveat that
applies to tools/redact/blur_figure2.py.

Usage:
    python patch_figure1_dedup_note.py <input_image> <output_image>
"""

import sys
import math
from PIL import Image, ImageDraw, ImageFont


def dashed_line(draw, p0, p1, color, dash=6, gap=5, width=2):
    x0, y0 = p0
    x1, y1 = p1
    length = math.hypot(x1 - x0, y1 - y0)
    if length == 0:
        return
    dx, dy = (x1 - x0) / length, (y1 - y0) / length
    dist = 0
    while dist < length:
        seg_end = min(dist + dash, length)
        draw.line(
            [(x0 + dx * dist, y0 + dy * dist), (x0 + dx * seg_end, y0 + dy * seg_end)],
            fill=color, width=width,
        )
        dist += dash + gap


def font(size):
    for name in ("ariali.ttf", "arial.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except Exception:
            continue
    return ImageFont.load_default()


def main():
    if len(sys.argv) != 3:
        print("Usage: python patch_figure1_dedup_note.py <input_image> <output_image>")
        sys.exit(1)

    src_path, dst_path = sys.argv[1], sys.argv[2]
    img = Image.open(src_path).convert("RGB")
    draw = ImageDraw.Draw(img)

    # Whiteout the stale callout box (generous margin beyond the detected
    # dashed border, set by visual inspection of this specific diagram).
    draw.rectangle((1055, 468, 1350, 618), fill=(255, 255, 255))

    gray = (150, 150, 150)
    x0, y0, x1, y1 = 1060, 472, 1345, 614
    r = 14
    dashed_line(draw, (x0 + r, y0), (x1 - r, y0), gray)
    dashed_line(draw, (x0 + r, y1), (x1 - r, y1), gray)
    dashed_line(draw, (x0, y0 + r), (x0, y1 - r), gray)
    dashed_line(draw, (x1, y0 + r), (x1, y1 - r), gray)

    f = font(17)
    lines = [
        "eventId-based dedup path",
        "implemented and deployed here",
        "(28 Aug 2026), not separately",
        "shown",
    ]
    ty = y0 + 18
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=f)
        lw = bbox[2] - bbox[0]
        cx = (x0 + x1) / 2
        draw.text((cx - lw / 2, ty), line, font=f, fill=(40, 40, 40))
        ty += 26

    img.save(dst_path)
    print("saved", dst_path)


if __name__ == "__main__":
    main()
